version: '3.8'

services:
  propresenter-viewer:
    build: .
    ports:
      - "10:80"
    container_name: propresenter-slide-viewer
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80 